export const SECTION = {
  ARTS: "arts",
  AUTOMOBILES: "automobiles",
  BOOKS: "books",
  BUSINESS: "business",
  FASHINON: "fashion",
  DINING: "dining",
  HEALTH: "health",
  INSIDER: "insider",
  MAGAZINE: "magazine",
  MOVIES: "movies",
  NY_REGION: "nyregion",
  OBITUARIES: "obituaries",
  OPINION: "opinion",
  POLITICS: "politics",
  REAL_ESTATE: "realestate",
  SCIENCE: "science",
  SPORTS: "sports",
  SUNDAY_REVIEW: "sundayreview",
  TECHNOLOGY: "technology",
  THEATER: "theater",
  T_MAGAZINE: "t-magazine",
  TRAVEL: "travel",
  UPSHOT: "upshot",
  US: "us",
  WORLD: "world",
  WELL: "well",
};
